//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentougou.UserControl {
    
    public partial class UC_ChannelInfo {
        protected System.Web.UI.WebControls.Literal ltrTypeImg;
        protected System.Web.UI.WebControls.Literal ltrName;
        protected System.Web.UI.WebControls.Literal ltrState;
        protected System.Web.UI.WebControls.Literal ltrBeginTime;
        protected System.Web.UI.WebControls.Literal ltrUserName;
        protected System.Web.UI.WebControls.Literal ltrCreateTime;
        protected System.Web.UI.WebControls.Literal ltrInfo;
        protected System.Web.UI.WebControls.Literal ltrBtn;
        protected System.Web.UI.WebControls.Literal ltAddressList;
    }
}
