//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentougou.UserControl {
    
    public partial class UC_ProgramList {
        protected System.Web.UI.WebControls.Literal ltrListTop;
        protected System.Web.UI.WebControls.Repeater rptProgramList;
        protected System.Web.UI.WebControls.Literal ltrEmpty;
        protected System.Web.UI.WebControls.Literal ltrListBtm;
    }
}
