//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentougou {
    
    public partial class ChannelLink {
        protected System.Web.UI.WebControls.DropDownList ddlType;
        protected System.Web.UI.WebControls.Literal ltrOper;
        protected System.Web.UI.HtmlControls.HtmlAnchor LinkDelete;
        protected System.Web.UI.WebControls.Literal ltrListTop;
        protected System.Web.UI.WebControls.Repeater rptChaLink;
        protected System.Web.UI.WebControls.Literal ltrEmpty;
        protected System.Web.UI.WebControls.Literal ltrListBtm;
        public new mentougou.MasterPage Master {
            get {
                return ((mentougou.MasterPage)(base.Master));
            }
        }
    }
}
