//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentougou {
    
    public partial class Default {
        protected mentougou.UserControl.UC_CatalogMix catalog1;
        protected mentougou.UserControl.UC_CastUI castui;
        protected mentougou.UserControl.UC_CatalogMix catalog3;
        protected mentougou.UserControl.UC_CatalogMix catalog4;
        protected mentougou.UserControl.UC_CatalogMix catalog5;
        protected mentougou.UserControl.UC_CatalogMix catalog6;
        public new mentougou.MasterPage Master {
            get {
                return ((mentougou.MasterPage)(base.Master));
            }
        }
    }
}
