//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentougou {
    
    public partial class MasterPage {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.WebControls.Literal ltrJS;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Panel pnlLogin;
        protected System.Web.UI.WebControls.TextBox tbUserName;
        protected System.Web.UI.WebControls.TextBox tbPassWord;
        protected System.Web.UI.WebControls.ImageButton ibtnLogin;
        protected System.Web.UI.WebControls.Panel pnlIsLogon;
        protected System.Web.UI.WebControls.Literal ltrUserName;
        protected System.Web.UI.WebControls.ImageButton ibtnExit;
        protected System.Web.UI.WebControls.Panel pnlSearch;
        protected System.Web.UI.WebControls.TextBox tbSearchText;
        protected System.Web.UI.WebControls.ImageButton ibtnSearch;
        protected mentougou.UserControl.UC_BulletinMarquee bulletinList;
        protected System.Web.UI.WebControls.Literal ltrPath;
        protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}
