//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentougou {
    
    public partial class ViewByClass {
        protected System.Web.UI.WebControls.Panel pnlCatalog;
        protected System.Web.UI.WebControls.Repeater rptCatalogList;
        protected mentougou.UserControl.UC_ProgramList UC_ProgramList1;
        public new mentougou.MasterPage Master {
            get {
                return ((mentougou.MasterPage)(base.Master));
            }
        }
    }
}
