<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="utf-8" />
    <link rel="stylesheet" href="theme/default/Style/program.css" type="text/css"/>    
    <link rel="stylesheet" type="text/css" href="Style/theme/alphacube.css" />  
    <script type="text/javascript" src="Scripts/prototype.js"></script>
    <script type="text/javascript" src="Scripts/window.js"></script>
    <script type="text/javascript" src="Scripts/mod.js"></script> 
    <title>$title$</title>    
</head>
<body>    
<div id="wrapper">
  <div id="toper">
    <div id="logo"><img src="Theme/default/Images/depend/$logo$" alt=""/></div>
    $Module$
  </div>
  <div id="topdomain"><img src="Theme/default/Images/depend/topdomain.gif" alt="" /></div>
  $CatalogNav$
  <div id="banner"><img src="Theme/default/Images/depend/banner.gif" alt=""/></div>
  <div id="primary">
    <div id="firster">     
      $LoginBox$
      $SearchBox$
      $ProgramTop$
      $SoftDown$
    </div>
    <div id="seconder">
      $righter$
    </div>
  </div> 
  $Footer$        
</div>
 <script type="text/javascript">   
    UpdateUserState();
 </script>
</body>
</html>