<div id="ProgramDetail">
    <h3><span>$RS.Detail$</span></h3>
    <div class="img">
        <table><tr><td>$Program.Image$</td></tr></table>
    </div>
    <ul class="item">
        <li class="title"><span class="info">$RS._Name$</span><b>$Program.Name$</b></li>
        <li><span>$RS.Point$: </span>$Program.Point$</li>
        <li><span>$RS.Director$: </span>$Program.Director$</li>
        <li><span>$RS.Actor$: </span>$Program.Actor$</li>
        <li><span>$RS.Length$: </span>$Program.Time$</li>
        <li><span>$RS.Class$: </span>$Program.Class$</li>
        <li><span>$RS.Kbps$: </span>$Program.Kbps$</li>
        <li><span>$RS.AddTime$: </span>$Program.AddTime$</li>
        <li><span>$RS.View$: </span>$Program.ReadCount$</li>
        <li class="btn">$Program.Play$ $Program.Download$ $Program.TimeLeft$</li>        
    </ul>
</div>