<table id="addPoint">
    <tr><td class="w1">$RS.CardNo$:</td><td class="w2"><input type="text" class="txt" id="txtNo" name="txtNo" /></td></tr>
    <tr><td class="w1">$RS.CardPwd$:</td><td class="w2"><input type="password" class="txt" id="txtPwd" name="txtPwd" /></td></tr>
    <tr><td class="w1"></td><td class="w2"> <input type="image" class="ibtn" src="Theme/default/Images/depend/btn_ok.gif" onclick="user.AddPoint();" alt=""/></td></tr>
</table>