//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.WebTd {
    
    public partial class MasterPage {
        protected System.Web.UI.HtmlControls.HtmlForm ModForm;
        protected MOD.WebTd.UserControls.UC_Toper Toper1;
        protected MOD.WebTd.UserControls.UC_CatalogNav CatalogNav1;
        protected MOD.WebTd.UserControls.UC_ProgramSearch seach1;
        protected MOD.WebTd.UserControls.UC_BulletinTop BulletinTop1;
        protected MOD.WebTd.UserControls.UC_ProgramTop ProgramTop;
        protected MOD.WebTd.UserControls.UC_ProgramNew ProgramNew1;
        protected MOD.WebTd.UserControls.UC_SoftDown Down1;
        protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
        protected MOD.WebTd.UserControls.UC_Footer Footer1;
    }
}
