//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.WebTd {
    
    public partial class Recorder {
        protected System.Web.UI.WebControls.Repeater rptLive;
        protected System.Web.UI.WebControls.Repeater rptMix;
        public new MOD.WebTd.VideoPage Master {
            get {
                return ((MOD.WebTd.VideoPage)(base.Master));
            }
        }
    }
}
