//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.WebTd {
    
    public partial class VideoPage {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm ModForm;
        protected MOD.WebTd.UserControls.UC_Toper Toper1;
        protected MOD.WebTd.UserControl.UC_BulletinMarquee CatalogNav1;
        protected System.Web.UI.WebControls.ContentPlaceHolder channelList;
        protected MOD.WebTd.UserControls.UC_Footer Footer1;
    }
}
