//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.UI {
    
    public partial class ChannelInfo {
        protected System.Web.UI.WebControls.Literal ltrTip;
        protected System.Web.UI.WebControls.Literal ltrLargeImg;
        protected System.Web.UI.WebControls.Literal ltrSmallImg;
        protected System.Web.UI.WebControls.Literal ltrCName;
        protected System.Web.UI.WebControls.Literal ltrStatus;
        protected System.Web.UI.WebControls.Literal ltrUserName;
        protected System.Web.UI.WebControls.Literal ltrCreateTime;
        protected System.Web.UI.WebControls.Literal ltrBeginTime;
        protected System.Web.UI.WebControls.Literal ltrCInfo;
        protected System.Web.UI.WebControls.Literal ltrPlay;
        protected System.Web.UI.WebControls.Literal ltAddressList;
        public new MOD.UI.VideoPage Master {
            get {
                return ((MOD.UI.VideoPage)(base.Master));
            }
        }
    }
}
