//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.UI {
    
    public partial class Charge {
        protected System.Web.UI.WebControls.TextBox tbCardNum;
        protected System.Web.UI.WebControls.TextBox tbCardPwd;
        protected System.Web.UI.WebControls.ImageButton ibtnAddPoint;
        protected System.Web.UI.WebControls.Label lblTips;
    }
}
