//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.UI {
    
    public partial class MasterPage {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected MOD.UI.UserControls.UC_Toper Toper1;
        protected MOD.UI.UserControls.UC_CatalogNav UC_CatalogNav1;
        protected MOD.UI.UserControls.UC_ProgramSearch ProgramSearch1;
        protected MOD.UI.UserControls.UC_ProgramTop ProgramTop1;
        protected MOD.UI.UserControls.UC_SoftDown softdown1;
        protected System.Web.UI.WebControls.ContentPlaceHolder rightHolder;
        protected MOD.UI.UserControls.UC_Footer UC_Footer1;
    }
}
