//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.UI {
    
    public partial class ModifyPwd {
        protected System.Web.UI.WebControls.TextBox txPdOld;
        protected System.Web.UI.WebControls.Label lblPwdOld;
        protected System.Web.UI.WebControls.TextBox txPdDefault;
        protected System.Web.UI.WebControls.Label lblPwdNew;
        protected System.Web.UI.WebControls.TextBox txPdConfirm;
        protected System.Web.UI.WebControls.Label lblPwdConfirm;
        protected System.Web.UI.WebControls.ImageButton ImageChangePwd;
    }
}
