//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.UI {
    
    public partial class ProgramVideo {
        protected MOD.UI.UserControls.UC_BulletinTop UC_BulletinTop1;
        protected MOD.UI.UserControls.UC_ProgramNew programnew1;
        protected MOD.UI.UserControls.UC_ProgramNewView programnew2;
    }
}
