//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.UI {
    
    public partial class Recorder {
        protected System.Web.UI.WebControls.Literal ltrTip;
        protected System.Web.UI.WebControls.Literal ltrLive;
        protected System.Web.UI.WebControls.Literal ltrMixc;
        protected System.Web.UI.WebControls.Literal ltrListTop;
        protected System.Web.UI.WebControls.Repeater rptChannelList;
        protected System.Web.UI.WebControls.Literal ltrEmpty;
        public new MOD.UI.VideoPage Master {
            get {
                return ((MOD.UI.VideoPage)(base.Master));
            }
        }
    }
}
