//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.UI {
    
    public partial class UserReg {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.TextBox tbRegMask;
        protected System.Web.UI.WebControls.TextBox tbRegName;
        protected System.Web.UI.WebControls.TextBox tbRegPwd;
        protected System.Web.UI.WebControls.TextBox tbConfirm;
        protected System.Web.UI.WebControls.TextBox tbRegInfo;
        protected System.Web.UI.WebControls.ImageButton ibtnAdd;
    }
}
