//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.WebTd.UserControls {
    
    public partial class UC_BulletinInfo {
        protected System.Web.UI.WebControls.Literal ltrName;
        protected System.Web.UI.WebControls.Literal ltrAddTime;
        protected System.Web.UI.WebControls.Literal ltrUserName;
        protected System.Web.UI.WebControls.Literal ltrInfo;
    }
}
