//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.WebTd.UserControls {
    
    public partial class UC_ProgramRemark {
        protected System.Web.UI.WebControls.Literal ltPage;
        protected System.Web.UI.WebControls.Repeater rptPrmRemark;
        protected System.Web.UI.WebControls.TextBox tbPrInfo;
        protected System.Web.UI.WebControls.ImageButton btnComment;
    }
}
