//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.WebTd.UserControls {
    
    public partial class UC_Toper {
        protected System.Web.UI.WebControls.Image imgLogo;
        protected System.Web.UI.WebControls.Panel pnlIsLogon;
        protected System.Web.UI.WebControls.LinkButton lbtnExit;
        protected System.Web.UI.WebControls.Literal ltrHelpNav;
        protected System.Web.UI.WebControls.Panel pnlLogin;
        protected System.Web.UI.WebControls.TextBox tbUserName;
        protected System.Web.UI.WebControls.TextBox tbPassWord;
        protected System.Web.UI.WebControls.ImageButton ibtnLogin;
        protected System.Web.UI.WebControls.Literal ltrSetting;
    }
}
