//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.WebTd.UserControls {
    
    public partial class Uc_Login {
        protected System.Web.UI.WebControls.Panel panelLogin;
        protected System.Web.UI.WebControls.TextBox tbUserName;
        protected System.Web.UI.WebControls.Label lbUserName;
        protected System.Web.UI.WebControls.TextBox tbPassWord;
        protected System.Web.UI.WebControls.Label lbInfo;
        protected System.Web.UI.WebControls.ImageButton btnLogin;
        protected System.Web.UI.WebControls.ImageButton btnLogout;
    }
}
