//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Admin.UserControls {
    
    public partial class UC_CatalogMng {
        protected System.Web.UI.WebControls.Literal ltrName;
        protected System.Web.UI.WebControls.Literal ltrRadioGroup;
        protected System.Web.UI.WebControls.Literal ltrBtn;
    }
}
