//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Admin.UserControls {
    
    public partial class UC_GroupEdit {
        protected System.Web.UI.WebControls.Literal ltrName;
        protected System.Web.UI.WebControls.Literal ltrClass;
        protected System.Web.UI.WebControls.Literal ltrChkLogin;
        protected System.Web.UI.WebControls.Literal ltrChkUserCourse;
        protected System.Web.UI.WebControls.Literal ltrChkProgram;
        protected System.Web.UI.WebControls.Literal ltrChkProgramItem;
        protected System.Web.UI.WebControls.Literal ltrChkCast;
        protected System.Web.UI.WebControls.Literal ltrChkCastItem;
        protected System.Web.UI.WebControls.Literal ltrChkSys;
        protected System.Web.UI.WebControls.Literal ltrChkSysItem;
        protected System.Web.UI.WebControls.Literal ltrInfo;
        protected System.Web.UI.WebControls.Literal ltrBtnEdit;
    }
}
