//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Admin.UserControls {
    
    public partial class UC_ProgramInfo {
        protected System.Web.UI.WebControls.Literal ltrImg;
        protected System.Web.UI.WebControls.Literal ltrImgView;
        protected System.Web.UI.WebControls.Literal ltrName;
        protected System.Web.UI.WebControls.Literal ltrCatalog;
        protected System.Web.UI.WebControls.Literal ltrDirector;
        protected System.Web.UI.WebControls.Literal ltrClass;
        protected System.Web.UI.WebControls.Literal ltrActor;
        protected System.Web.UI.WebControls.Literal ltrPublish;
        protected System.Web.UI.WebControls.Literal ltrTime;
        protected System.Web.UI.WebControls.Literal ltrKbps;
        protected System.Web.UI.WebControls.Literal ltrReadCount;
        protected System.Web.UI.WebControls.Literal ltrAddTime;
        protected System.Web.UI.WebControls.Literal ltrAddUser;
        protected System.Web.UI.WebControls.Literal ltrPoint;
        protected System.Web.UI.WebControls.Literal ltrOperator;
    }
}
