//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Admin.UserControls {
    
    public partial class UC_SysSetExpand {
        protected System.Web.UI.WebControls.Literal ltrFuncImg1;
        protected System.Web.UI.WebControls.Literal ltrName1;
        protected System.Web.UI.WebControls.Literal ltrLink1;
        protected System.Web.UI.WebControls.Literal ltrFuncImg2;
        protected System.Web.UI.WebControls.Literal ltrName2;
        protected System.Web.UI.WebControls.Literal ltrLink2;
        protected System.Web.UI.WebControls.Literal ltrFuncImg3;
        protected System.Web.UI.WebControls.Literal ltrName3;
        protected System.Web.UI.WebControls.Literal ltrLink3;
    }
}
