//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.Admin.UserControls {
    
    public partial class UC_UserEdit {
        protected System.Web.UI.WebControls.Literal ltrMask;
        protected System.Web.UI.WebControls.Literal ltrName;
        protected System.Web.UI.WebControls.Literal ltrPass;
        protected System.Web.UI.WebControls.Literal ltrPassConfirm;
        protected System.Web.UI.WebControls.Literal ltrChkLogin;
        protected System.Web.UI.WebControls.Literal ltrChkModifyPass;
        protected System.Web.UI.WebControls.Literal ltrInfo;
        protected System.Web.UI.WebControls.Literal ltrGroupList;
        protected System.Web.UI.WebControls.Literal ltrBtnEdit;
    }
}
