//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.UI.UserControls {
    
    public partial class UC_BulletinList {
        protected System.Web.UI.WebControls.Literal ltrTip;
        protected System.Web.UI.WebControls.Literal ltrListTop;
        protected System.Web.UI.WebControls.Repeater rptBullist;
        protected System.Web.UI.WebControls.Literal ltrEmpty;
    }
}
