//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.UI.UserControls {
    
    public partial class UC_GuestBookAdd {
        protected System.Web.UI.HtmlControls.HtmlInputText txtSubject;
        protected System.Web.UI.HtmlControls.HtmlTextArea txtInfo;
        protected System.Web.UI.HtmlControls.HtmlInputRadioButton gbType0;
        protected System.Web.UI.HtmlControls.HtmlInputRadioButton gbType1;
        protected System.Web.UI.WebControls.Label lblTips;
    }
}
