//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.UI.UserControls {
    
    public partial class UC_ProgramInfo {
        protected System.Web.UI.WebControls.Literal ltrImg;
        protected System.Web.UI.WebControls.Literal ltrName;
        protected System.Web.UI.WebControls.Literal ltrPoint;
        protected System.Web.UI.WebControls.Literal ltrDirector;
        protected System.Web.UI.WebControls.Literal ltrActor;
        protected System.Web.UI.WebControls.Literal ltrTime;
        protected System.Web.UI.WebControls.Literal ltrClass;
        protected System.Web.UI.WebControls.Literal ltrKbps;
        protected System.Web.UI.WebControls.Literal ltrAddtime;
        protected System.Web.UI.WebControls.Literal ltrReadCount;
        protected System.Web.UI.WebControls.Literal ltrPlay;
        protected System.Web.UI.WebControls.Literal ltrTimeLeft;
        protected System.Web.UI.WebControls.Literal ltrIntro;
        protected System.Web.UI.HtmlControls.HtmlGenericControl tabPage2;
        protected MOD.UI.UserControls.UC_ProgramRemark UC_ProgramRemark1;
        protected MOD.UI.UserControls.UC_ProgramChapter UC_ProgramChapter1;
        protected System.Web.UI.HtmlControls.HtmlGenericControl tabPage4;
        protected System.Web.UI.WebControls.Repeater rptMediaServer;
    }
}
