//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD.UI {
    
    public partial class VideoPage {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected MOD.UI.UserControls.UC_Toper Toper1;
        protected MOD.UI.UserControl.UC_BulletinMarquee UC_BulletinMarquee1;
        protected System.Web.UI.WebControls.ContentPlaceHolder rightHolder;
        protected MOD.UI.UserControls.UC_Footer Footer1;
    }
}
