<div class="mark">
    <div class="left"><img src="Theme/webtd/Images/depend/pro_chapter_list.gif" alt=""/><span>$RS._Chapter$</span></div>
    <div class="right"></div>  
</div>    
<ul id="chapter">    
$Chapter:{
   <li><a href="javascript://" onclick="OpenPlay('$it.ProgramID$',$it.Order$,$it.MediaKind$);">$it.Name$</a>
       <span class="time">($it.Time$)</span>
   </li>
}$   
</ul>


    
                     
